benchtests/Makefile:Fix naming conflict
/home/crafcat7/ext2/vela/vela-dev/external/benchtests/port/support/support.c:127: multiple definition of `xasprintf'; /home/crafcat7/ext2/vela/vela-dev/nuttx/staging/libapps.a(util.c.home.crafcat7.ext2.vela.vela-dev.apps.system.fdt_1.o):/home/crafcat7/ext2/vela/vela-dev/nuttx/libs/libc/fdt/dtc/util.c:82: first defined here

Signed-off-by: chenrun1 <chenrun1@xiaomi.com>